### ISSUE TITLE
Public access : redirect after successful login

### ISSUE THREAD

**Issue by faulomi** [chvndb/keycloak-spring-vaadin-demo#2]
Hi,

First, thanks for sharing your work on that topic, I'm currently integrating the same security stack.
This is more a question than an issue actually, but I'm currently testing the public access and I have a hard time finding the proper configuration to correctly handle the user navigation .

My use case is the following : 
1. I have some public pages (Or view in Vaadin terminology) and private pages within the same application.
2. From the public page, I can navigate to a private page (only accessible for customers for example), using the Vaadin Navigator.
3.  At this point, Spring Security would detect that I'm not authenticated, so I would like the user to be redirected to the login page  (basically, what you are doing by calling Page.getCurrent().setLocation().
4. After an successful authentication, the user is redirected **to the initial view he wanted to access at the first place**.

This is a tricky point. As at step 3, we've specified the authentication entry point (/sso/login), the information about the view the user tried to access is lost. It means that he is simply redirected to sso/login url after a successful authentication, and he ends up on the landing page of the application(/).

Do you have any idea how to handle this flow correctly ? I only have hacks in mind for now, but maybe I'm missing the obvious solution. 

My current idea is to pass some query parameters to the sso/login entry point and when the user is redirected back to the application, I parse these query parameters to navigate to the right view.

That raises another question, what would be the proper component to implement this logic ?
I can see that Vaadin Security extension provides a VaadinAuthenticationSuccessHandler but I'm not sure this is the right approach yet.

Thank you for your insights,
Regards,

**Comment by chvndb** [comment]
Hi there, glad you like the demo.

I haven't tested your particular case, but the easiest solution would be to use HTML5 push state. This would get rid of the hashtags notation.

E.g.: `http://my.company.com/#!someview` becomes `http://my.company.com/someview`.

Then Keycloak will correctly redirect you to the view the user was navigating to.

An explanation can be found [in this blog](https://blog.akquinet.de/2017/07/28/navigating-vaadin-8/).

There is also a [Vaadin plugin](https://vaadin.com/directory#!addon/historyapinavigationstatemanager-add-on) that might be useful to look at.

**Comment by chvndb** [comment]
Closing due to no more reply
