### ISSUE TITLE
No Connection on localhost

### ISSUE THREAD

**Issue by capjoh** [chvndb/keycloak-spring-vaadin-demo#3]
Hey,

I've downloaded your repository for testing with docker, keycloak and so one. The commands "./gradlew network" and "./gradlew start" went successfully to the message:

> Building 75% > :bootRun

But I can't open the Admin-Console http://localhost:5050/auth/admin/master/console in the browser. I've get an "Unable to connect" message.

I've installed the requirements:
Apache Maven 3.3.9
git version 2.7.4
Java version: 1.8.0_151, vendor: Oracle Corporation
Docker version 17.09.0-ce, build afdb6d4
docker-compose version 1.8.0, build unknown

So, can you help me?

Thank you.
Best regards

**Comment by chvndb** [comment]
Can you provide the output of `docker ps -a` and `docker logs demo_keycloak`. 

Also, what do you get when you access `http://localhost:8080/` and `http://localhost:5050/auth/`?

**Comment by capjoh** [comment]
Here is the output of the command `./gradlew network`

```
Starting a Gradle Daemon (subsequent builds will be faster)
:network

BUILD SUCCESSFUL

Total time: 6.066 secs

```
Here is the output (last four lines) of the command `./gradlew start`

```
2017-11-23 10:13:49.659 DEBUG 7000 --- [  restartedMain] s.s.c.a.a.b.AuthenticationManagerBuilder : No authenticationProviders and no parentAuthenticationManager defined. Returning null.
2017-11-23 10:13:49.694  INFO 7000 --- [  restartedMain] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-11-23 10:13:49.841  INFO 7000 --- [  restartedMain] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2017-11-23 10:13:49.851  INFO 7000 --- [  restartedMain] demo.vaadin.Application                  : Started Application in 9.378 seconds (JVM running for 10.16)
```

Here is the output of the command `docker ps -a` as a normal user

Got permission denied while trying to connect to the Docker daemon socket at `unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.32/containers/json?all=1: dial unix /var/run/docker.sock: connect: permission denied`

Here is the output of the command `docker ps -a` as the root user

```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                    PORTS               NAMES
58b65440284a        hello-world         "/hello"            20 hours ago        Exited (0) 20 hours ago                       unruffled_bell
```

Here is the output of the command `docker logs demo_keycloak`
`
Error response from daemon: No such container: demo_keycloak`

Here is the output of the command `curl http://localhost:8080 -v`

```
* Rebuilt URL to: http://localhost:8080/
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 401 
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Set-Cookie: JSESSIONID=F750A42E64C8102F4802B3ACC06721F7; Path=/; HttpOnly
< WWW-Authenticate: Bearer realm="Unknown"
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Thu, 23 Nov 2017 09:18:06 GMT
< 
* Connection #0 to host localhost left intact
{"timestamp":1511428686286,"status":401,"error":"Unauthorized","message":"Unauthorized","path":"/"}

```
Here is the output of the command `curl http://localhost:5050/auth/ -v`

```
*   Trying 127.0.0.1...
* connect to 127.0.0.1 port 5050 failed: Connection refused
* Failed to connect to localhost port 5050: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 5050: Connection refused
```

**Comment by chvndb** [comment]
Well the issue is clear, the containers did not start. This can be seen from the output of `docker ps -a`. The cause seems to be a permissions issue.

It looks like your user does not have permission to run any `docker` or `docker-compose` commands. Is your user in the [docker group](https://docs.docker.com/engine/installation/linux/linux-postinstall/)?

The `./gradlew start` command triggers the following command: `docker-compose -f src/main/docker/application.yml up -d`. You can see that in the `build.gradle` file. If you do not have the correct permissions it will silently fail but still run the Spring Boot application. 

Therefore, the application runs but not Keycloak and authentication is not possible.

You can either add the correct permissions to your user or try to execute `./gradlew start` as root.

**Comment by capjoh** [comment]
Yes, my user is in the docker group and can execute the commands. I've executed the commands as root also but nothing changes. So, I'll be create an another virtual machine for testing and I'll be give you a feedback later.

**Comment by capjoh** [comment]
I've tested this environment in an another virtual machine and it worked very well. Thanks for you help and your support.
